---
title: "MBM_Biota"
author: "Maddy Enda"
format: html
editor: visual
eval: true
echo: true 
warning: false
message: false
---

### Biota Data: Load packages and preliminary exploration

```{r}
# Load relevant libraries
library(tidyverse)
library(dplyr)
library(terra)
library(tmap)
library(sf)
library(here)
library(stars)
library(janitor)
```

```{r}
# Read in the pre-filtered Biota data set that only has CA observations
biota_data <- readRDS("Biota.rds") 
```

```{r}
# Preliminary exploration of biota data
colnames(biota_data)

# Number of observations and columns for our df
dim(biota_data)
```

### MPA Boundary: clean and filter

```{r}
# Load in the MPA boundary data
MPA_boundary <- sf::st_read("data/California_Marine_Protected_Areas_[ds582]")

mpa <- MPA_boundary %>%
   clean_names() %>%
  filter(name == "Point Lobos SMR") %>%
  # Select relevant columns
  select(-c("objectid", "ccr", "area_sq_mi", "study_regi", "fullname", "ccr_int", "shortname","acres", "shape_are", "shape_len")) %>%
  mutate(area_km_mpa = hectares / 100) %>%  # Convert hectares to square km
  select(-hectares)
```

### Join Biota data to MPA data

```{r}
# Convert the shape_area column in km

# Reproject to a UTM Zone (Example: UTM Zone 10N for the U.S. West Coast)
biota_transform <- st_transform(biota_data, crs = 32610)  # Change EPSG based on your region

# Calculate the area in square meters
biota_transform$Biota_Area_m2 <- st_area(biota_transform)

# Convert to square kilometers
biota_transform$Biota_Area_km2 <- biota_transform$Biota_Area_m2 / 1e6

# Print first few rows with updated area values
print(head(biota_transform[, c("Biota_Area_m2", "Biota_Area_km2")]))
```

```{r}
# Check CRS of both data sets
st_crs(biota_transform)== st_crs(mpa)

# Match CRS
mpa_transform <- st_transform(mpa, crs = st_crs(biota_transform))

# Perform spatial join: Keep MPA columns and match substrate data
mpa_lobos <- st_join(mpa_transform, biota_transform, left = TRUE)
```

```{r}
colnames(mpa_lobos)
```

```{r}
# Check the class of the new column
class(mpa_lobos$Biota_Area_km2)

# Convert the data type of Biota_Area_km2 to match area_km_mpa
mpa_lobos$Biota_Area_km2 <- as.numeric(mpa_lobos$Biota_Area_km2)
```

```{r}
# Find percentage of each biota in the MPA
mpa_lobos <- mpa_lobos %>%
  mutate(pct_biota = (Biota_Area_km2 / area_km_mpa) * 100) %>%
  filter(Biota_Area_km2 <= area_km_mpa)
```

```{r}
# Group the data by category
mpa_group <- mpa_lobos %>%
  group_by( CMECS_BC_Category) %>%
  summarise(
    sum_biota = sum(Biota_Area_km2, na.rm = TRUE),  
    sum_mpa = sum(area_km_mpa, na.rm = TRUE)  
  ) %>%
  mutate(pct_mpa_biota = (sum_biota / sum_mpa) * 100)  
```

```{r}
head(mpa_group)
```

```{r}
# Visualize results
ggplot(mpa_group, aes(x = CMECS_BC_Category, y = pct_mpa_biota)) +
  geom_col() +
  labs(title = "Marine Biota Type by Area(km2) in Point Lobos SMR",
       x = "Biota Category",
       y = "Percentage") +
  theme_bw() +
  geom_text(aes(label = round(pct_mpa_biota, 2), hjust = 0.5, vjust = 0.01)) 
```

### Substrate Data: Filter and explore

```{r}
# Read in pre-saved Substrate file, filtered to CA
substrate_data <- readRDS("Substrate.rds")

# Check colnames
colnames(substrate_data)
```

```{r}
# Rename the columns and clean the data
substrate_data <- substrate_data %>%
  rename(
    region = pmep_region,
    group = cmecs_sc_name,
    subgroup = cmecs_sc_subgroup,
    level_id = cmecs_sc_level,
    class_type = cmecs_sc_class,  
    subclass = cmecs_sc_subclass,
    bio_gen_group = cmecs_sc_group,
    noaa_hapc = noaa_hapc,
    estuary_name = estuary_name,
    area_ha = area_ha,
    shape_length = shape_length,
    shape_area = shape_area
  ) %>% 
  mutate(area_km_sub = area_ha / 100) %>%  # Convert hectares to square km
  select(-area_ha)  # Remove the original area_ha column
  
```

### Join Substrate data to mpa_lobos

```{r}
# Reproject to a UTM Zone (Example: UTM Zone 10N for the U.S. West Coast)
substrate_transform <- st_transform(substrate_data, crs = 32610)  # Change EPSG based on your region

# Calculate the area in square meters
substrate_transform$Substrate_Area_m2 <- st_area(substrate_transform)

# Convert to square kilometers
substrate_transform$Substrate_Area_km2 <- substrate_transform$Substrate_Area_m2 / 1e6

# Print first few rows with updated area values
print(head(substrate_transform[, c("Substrate_Area_m2", "Substrate_Area_km2")]))
```

```{r}
# Check CRS of both data sets
st_crs(substrate_transform)== st_crs(mpa_lobos)

# Perform spatial join: Keep MPA columns and match substrate data
mpa_lobos_total <- st_join(mpa_lobos, substrate_transform, left = TRUE)
```
```{r}
# Save the total mpa_lobos_total as a .RDS
saveRDS(mpa_lobos_total, file="Point_Lobos_MPA.rds")
```

```{r}
# Find percentage of each substrate in the MPA
mpa_lobos_total <- mpa_lobos_total %>%
  mutate(pct_sub = (area_km_sub / area_km_mpa) * 100) %>%  # Calculate percentage
    filter(area_km_sub <= area_km_mpa)
```

```{r}
colnames(mpa_lobos_total)
```



```{r}
# Group the data by substrate group
mpa_group_total <- mpa_lobos_total %>%
  group_by(group, CMECS_BC_Category) %>%
  summarise(
    sum_sb = sum(area_km_sub, na.rm = TRUE),
    sum_mpa = sum(area_km_mpa, na.rm = TRUE),
    sum_biota = sum(Biota_Area_km2, na.rm = TRUE))  %>%
  mutate(pct_substrate = (sum_sb / sum_mpa) * 100)  %>%
  mutate(pct_biota = (sum_biota / sum_mpa) * 100) 
```

### Making a treemap for Point Lobos MPA

```{r}
treemap(data,
    index = c("group", "subgroup"), vSize = "value",
    type = "index", # How you color the treemap. type help(treemap) for more info
    palette = "Set1", # Select your color palette from the RColorBrewer presets or make your own.
    title = "My Treemap", # Customize your title
    fontsize.title = 12, # Size of the title
)
```
