---
title: "bioregion_central_biota_analysis"
author: "Maddy Enda"
format: html
editor: visual
---

### Call libraries

```{r}
# Load in the packages for this data analysis
librarian::shelf(tidyverse, dplyr, terra, tmap, sf, here, stars, janitor, units)
```

### Load in the central California data

```{r}
# Read in the prefiltered biota data from the database
rds.dir <- "/capstone/marinebiomaps/data/rds-files"
cencal_biota <- readRDS(file.path(rds.dir, "ccsr_biota.rds"))
```

```{r}
# Remove the unclassified observations
biota_clean <- cencal_biota %>%
  filter(cmecs_bc_category != "Unclassified")
```

### Find Percentage of each Biota type in SoCal

```{r}
# Drop the geometries to speed up run time
cencal_biota_simple <- biota_clean %>%
  st_drop_geometry()
```

```{r}
# Create a column that has the total area of socal biota
cencal_biota_simple <- cencal_biota_simple %>%
  mutate(total_area = sum(area_ha))

# Create a sum of area column in mpa_transform
cencal_biota_simple_2 <- cencal_biota_simple %>%
  group_by(cmecs_bc_category) %>%  # Group by MPA type, substrate group
  summarise(
    biota_area = sum(area_ha, na.rm = TRUE),  
    total_area = first(total_area)  
  ) %>%
  mutate(pct_biota = (biota_area / total_area) * 100)
```

```{r}
# Find percentage of each biota in the SoCal
# Visualize results
ggplot(cencal_biota_simple_2, aes(x = reorder(cmecs_bc_category, pct_biota), y = pct_biota, fill = cmecs_bc_category)) +
  geom_col() +
  labs(title = " Biota Distribution in the \n\ Central California Bioregion (CCSR) MPAs",
       y = "Percentage of Total Biota") +
    geom_text(aes(label = paste0(round(pct_biota, 1), "%"), hjust = 0.5, vjust = 0.01, size= 1, family= "montserrat"),) +  
  geom_text(aes(label = paste0(round(pct_biota, 1), "%"), hjust = 0.5, vjust = 0.01, size= 1, family= "montserrat")) +
  theme_classic() +
  scale_fill_manual(values = biota_pal) +
  theme(plot.title = element_text(family= "montserrat", size= 15),
        legend.position = "none",
        legend.title = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y= element_text(size= 10, family= "montserrat"),
    axis.title.y = element_blank(),
    axis.title.x= element_text(size= 10, family= "montserrat")
     )+
  coord_flip()
```

### Load in our northern/central California data

```{r}
# Read in the prefiltered biota data from the database
rds.dir <- "/capstone/marinebiomaps/data/rds-files"
norcencal_biota <- readRDS(file.path(rds.dir, "nccsr_biota.rds"))
```

```{r}
# Remove the unclassified observations
biota_clean <- norcencal_biota %>%
  filter(cmecs_bc_category != "Unclassified")
```

### Load in MPA Boundaries

```{r}
# Load in the MPA boundary data
MPA_boundary <- sf::st_read("data/California_Marine_Protected_Areas_[ds582]")

# Filter to Point Lobos locations
mpa <- MPA_boundary %>%
   clean_names()
```

### Find Percentage of each Biota type in SoCal

```{r}
# Drop the geometries to speed up run time
norcencal_biota_simple <- biota_clean %>%
  st_drop_geometry()
```

```{r}
# Create a column that has the total area of socal biota
norcencal_biota_simple <- norcencal_biota_simple %>%
  filter(cmecs_bc_category != "Floating/Suspended Plants and Macroalgae") %>%
  filter(cmecs_bc_category != "Seagrass Bed") %>%
  mutate(total_area = sum(area_ha))

# Create a sum of area column in mpa_transform
norcencal_biota_simple_2 <- norcencal_biota_simple %>%
  group_by(cmecs_bc_category) %>%  # Group by MPA type, substrate group
  summarise(
    biota_area = sum(area_ha, na.rm = TRUE),  
    total_area = first(total_area)  
  ) %>%
  mutate(pct_biota = (biota_area / total_area) * 100)
```

```{r}
# Find percentage of each biota in the SoCal
# Visualize results
ggplot(norcencal_biota_simple_2, aes(x = reorder(cmecs_bc_category, pct_biota), y = pct_biota, fill = cmecs_bc_category)) +
  geom_col() +
  labs(title = " Biota Distribution in the Northern-Central \n\ California Bioregion (NCCSR) MPAs",
       y = "Percentage of Total Biota") +
    geom_text(aes(label = paste0(round(pct_biota, 1), "%"), hjust = 0.5, vjust = 0.01, size= 1, family= "montserrat"),) +  
  geom_text(aes(label = paste0(round(pct_biota, 1), "%"), hjust = 0.5, vjust = 0.01, size= 1, family= "montserrat")) +
  theme_classic() +
  scale_fill_manual(values = biota_pal) +
  theme(plot.title = element_text(family= "montserrat", size= 15),
        legend.position = "none",
        legend.title = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y= element_text(size= 10, family= "montserrat"),
    axis.title.y = element_blank(),
    axis.title.x= element_text(size= 10, family= "montserrat")
     )+
  coord_flip()
```

